name: ci

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Install fasm
      run: sudo apt-get update && sudo apt-get install -y fasm
    - name: make
      run: make
    - name: make v5
      run: make -C v5
