name: ci

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "tap" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
      with:
        submodules: recursive
    - name: make
      run: make
    - name: prove
      run: prove lang
