name: ci

on:
  pull_request:
    branches: [ "main", "ci" ]
  push:
    branches: [ "main", "ci" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: make
      uses: make
